In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Proccessed_Texas_Employment_ACS_2015_Texas.csv',header=0)
df.head()

,Unnamed: 0,ID,ST,PUMA,JWMNP,SCHL,WAGP,WKHP,WKW,ESR,...,JWAP,JWDP,SOCP,POWPUMA,POWSP,NWAB,NWAV,NWLA,NWLK,AGEP
0,0,1,48,1907,40.0,Post_Graduation,35000.0,50.0,1.0,1.0,...,Quarter_2,Quarter_2,General Services,Assigned POW,48.0,3.0,5.0,3.0,3.0,61
1,1,2,48,1907,0.0,School,0.0,0.0,0.0,6.0,...,Work_from_Home,Work_from_Home,Not a Worker,Not Worker or Under16,0.0,3.0,5.0,3.0,3.0,67
2,2,3,48,1907,0.0,School,0.0,0.0,0.0,6.0,...,Work_from_Home,Work_from_Home,Not a Worker,Not Worker or Under16,0.0,3.0,5.0,3.0,3.0,80
3,3,4,48,5202,0.0,No_Schooling,70000.0,40.0,1.0,1.0,...,Work_from_Home,Work_from_Home,businnes_and_finance,Assigned POW,48.0,3.0,5.0,3.0,3.0,33
4,4,5,48,5202,60.0,HighSchool,65000.0,55.0,1.0,1.0,...,Quarter_1,Quarter_1,General Services,Assigned POW,48.0,3.0,5.0,3.0,3.0,39

In [3]:
df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194483 entries, 0 to 194482
Data columns (total 22 columns):
Unnamed: 0    194483 non-null int64
ID            194483 non-null int64
ST            194483 non-null int64
PUMA          194483 non-null int64
JWMNP         194483 non-null float64
SCHL          194483 non-null object
WAGP          194483 non-null float64
WKHP          194483 non-null float64
WKW           194483 non-null float64
ESR           194483 non-null float64
FOD1P         194483 non-null object
NAICSP        194483 non-null object
JWAP          194483 non-null object
JWDP          194483 non-null object
SOCP          194483 non-null object
POWPUMA       194483 non-null object
POWSP         194483 non-null float64
NWAB          194483 non-null float64
NWAV          194483 non-null float64
NWLA          194483 non-null float64
NWLK          194483 non-null float64
AGEP          194483 non-null int64
dtypes: float64(10), int64(5), object(7)
memory usage: 32.6+ MB

In [4]:
# To convert categorial variable to numeric
# Using dummy variable
# Number of dummy variables = Number of category - 1
# Dummies a pandas method
# drop_first to have number of categorical variable - 1
df=pd.get_dummies(df,drop_first=True)

In [5]:
df.head()

,Unnamed: 0,ID,ST,PUMA,JWMNP,WAGP,WKHP,WKW,ESR,POWSP,...,JWDP_Quarter_4,JWDP_Work_from_Home,SOCP_General Services,SOCP_Medical,SOCP_Militay and Law Enforcement,SOCP_Not a Worker,SOCP_Technical,SOCP_businnes_and_finance,POWPUMA_Not Work in USA or Puerto,POWPUMA_Not Worker or Under16
0,0,1,48,1907,40.0,35000.0,50.0,1.0,1.0,48.0,...,0,0,1,0,0,0,0,0,0,0
1,1,2,48,1907,0.0,0.0,0.0,0.0,6.0,0.0,...,0,1,0,0,0,1,0,0,0,1
2,2,3,48,1907,0.0,0.0,0.0,0.0,6.0,0.0,...,0,1,0,0,0,1,0,0,0,1
3,3,4,48,5202,0.0,70000.0,40.0,1.0,1.0,48.0,...,0,1,0,0,0,0,0,1,0,0
4,4,5,48,5202,60.0,65000.0,55.0,1.0,1.0,48.0,...,0,0,1,0,0,0,0,0,0,0

In [6]:
# for splitting data 
X=df.loc[:,df.columns!='WAGP']
y=df['WAGP']
from sklearn.model_selection import train_test_split 
# If randam_state is constant we get the same split every time
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [7]:
from sklearn.svm import SVR

In [ ]:
# Linear SVM
from sklearn.svm import SVR
linear_svm=SVR(kernel='linear',C=1000)
linear_svm.fit(X_train,y_train)
y_train_pred=linear_svm.predict(X_train,y_train)
y_test_pred=linear_svm.predict(X_test,y_test)
# Linear Model Performance
from sklearn.metrics import mean_squared_error,r_score
print('Train MSE -',mean_squared_error(y_train,y_train_pred))
print('Test MSE - ',mean_squared_error(y_test,y_test_pred))
print('Train R2 - ',r2_score(y_train,y_train_pred))
print('Test R2 - ',r2_score(y_test,y_test_pred))

In [ ]:
# rbf SVM
from sklearn.svm import SVR
rbf_svm=SVR(kernel='rbf',C=1000)
rbf_svm.fit(X_train,y_train)
y_train_pred=rbf_svm.predict(X_train,y_train)
y_test_pred=rbf_svm.predict(X_test,y_test)
# Linear Model Performance
from sklearn.metrics import mean_squared_error,r_score
print('Train MSE -',mean_squared_error(y_train,y_train_pred))
print('Test MSE - ',mean_squared_error(y_test,y_test_pred))
print('Train R2 - ',r2_score(y_train,y_train_pred))
print('Test R2 - ',r2_score(y_test,y_test_pred))

In [ ]:
# ploy SVM
from sklearn.svm import SVR
poly_svm=SVR(kernel='poly',C=1000)
poly_svm.fit(X_train,y_train)
y_train_pred=poly_svm.predict(X_train,y_train)
y_test_pred=poly_svm.predict(X_test,y_test)
# Linear Model Performance
from sklearn.metrics import mean_squared_error,r_score
print('Train MSE -',mean_squared_error(y_train,y_train_pred))
print('Test MSE - ',mean_squared_error(y_test,y_test_pred))
print('Train R2 - ',r2_score(y_train,y_train_pred))
print('Test R2 - ',r2_score(y_test,y_test_pred))

In [8]:
# Hyper parameter tunning - Kernel - Linear 
from sklearn.model_selection import GridSearchCV
linear_svm=SVR(kernel='linear')
param_grid={'C':[0.1,0.5,1,2,3,4,5]}
linear_svm_grid_cv=GridSearchCV(linear_svm,param_grid,n_jobs=-1,cv=3,verbos=-1)
linear_svm_grid_cv.fit(X_train,y_train)
linear_svm=linear_svm_grid_cv.best_params_
y_train_pred=linear_svm.predict(X_train,y_train)
y_test_pred=linear_svm.predict(X_test,y_test)
# Linear Model Performance
from sklearn.metrics import mean_squared_error,r_score
print('Train MSE -',mean_squared_error(y_train,y_train_pred))
print('Test MSE - ',mean_squared_error(y_test,y_test_pred))
print('Train R2 - ',r2_score(y_train,y_train_pred))
print('Test R2 - ',r2_score(y_test,y_test_pred))

In [ ]:
# Hyper parameter tunning - Kernal - rbf
from sklearn.model_selection import GridSearchCV
rbf_svm=SVR(kernel='rbf')
param_grid={'C':[0.1,0.5,1,2,3,4,5],
           'gamma':[0.001,0.01,0.1,1,2,3,4]}
rbf_svm_grid_cv=GridSearchCV(rbf_svm,param_grid,n_jobs=-1,cv=3,verbos=-1)
rbf_svm_grid_cv.fit(X_train,y_train)
rbf_svm=rbf_svm_grid_cv.best_params_
y_train_pred=rbf_svm.predict(X_train,y_train)
y_test_pred=rbf_svm.predict(X_test,y_test)
# Linear Model Performance
from sklearn.metrics import mean_squared_error,r_score
print('Train MSE -',mean_squared_error(y_train,y_train_pred))
print('Test MSE - ',mean_squared_error(y_test,y_test_pred))
print('Train R2 - ',r2_score(y_train,y_train_pred))
print('Test R2 - ',r2_score(y_test,y_test_pred))

In [ ]:
# Hyper parameter tunning - Kernal - 
from sklearn.model_selection import GridSearchCV
poly_svm=SVR(kernel='poly')
param_grid={'C':[0.1,0.5,1,2,3,4,5],
            'gamma':[0.001,0.01,0.1,1,2,3,4]}
poly_svm_grid_cv=GridSearchCV(poly_svm,param_grid,n_jobs=-1,cv=3,verbos=-1)
poly_svm_grid_cv.fit(X_train,y_train)
poly_svm=poly_svm_grid_cv.best_params_
y_train_pred=poly_svm.predict(X_train,y_train)
y_test_pred=poly_svm.predict(X_test,y_test)
# Linear Model Performance
from sklearn.metrics import mean_squared_error,r_score
print('Train MSE -',mean_squared_error(y_train,y_train_pred))
print('Test MSE - ',mean_squared_error(y_test,y_test_pred))
print('Train R2 - ',r2_score(y_train,y_train_pred))
print('Test R2 - ',r2_score(y_test,y_test_pred))